/*
 *  CAN_Lcfg.c
 *
 *  Created on: April 23, 2021
 *      Author: Ghada & Toaa
 */

#include <stdio.h>
#include <stdlib.h>
#include "CAN.h"
#include "CAN_Lcfg.h"
#include "CAN_cfg.h"

filter_type CAN_filters_Array [ NUMBER_OF_CONFIGURED_CAN_FILTERS ] =
{
	{CANHANDLER_u8NEXTMSGREQUEST, REMOTE_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8GUIUPDATEACCEPT, REMOTE_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8ECUSWVERSION, DATA_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8GETFLASHBANK, DATA_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8ECUDTCs, DATA_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8ECUDTCs, REMOTE_FRAME, STANDARD_FORMAT}
};
