/*
 *  CAN_Lcfg.c
 *
 *  Created on: April 23, 2021
 *      Author: Ghada & Toaa
 */


CAN_msg CAN_ConfigArray[ NUMBER_OF_CONFIGURED_CAN  ]=
{
		{id, data[8], len, format, type, u8ActiveFlag, call back func },
};

filter_type CAN_filters_Array [ NUMBER_OF_CONFIGURED_CAN_FILTERS ] =
{
	{CANHANDLER_u8NEXTMSGREQUEST, REMOTE_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8GUIUPDATEACCEPT, REMOTE_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8ECUSWVERSION, DATA_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8GETFLASHBANK, DATA_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8ECUDTCs, DATA_FRAME, STANDARD_FORMAT},
	{CANHANDLER_u8ECUDTCs, REMOTE_FRAME, STANDARD_FORMAT}
};
